{
 "title": "测试数据",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(sec_restful_finder_action_sum[5m]) \n/ \nrate(sec_restful_finder_action_count[5m])) by (key)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "执行次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(sec_restful_finder_action_count[5m])) by (key)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口总览",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sec_restful_finder_api", "legendFormat": "__auto" }
   ]
  }
 ]
}